"""empty message

Revision ID: 1218f1208007
Revises: 6d092bc1e3ba
Create Date: 2024-02-25 02:14:08.085086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1218f1208007'
down_revision: Union[str, None] = '6d092bc1e3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('student_id_idx', 'student_course', ['student_id'], unique=False)
    op.create_index('course_id_idx', 'student_course', ['course_id'], unique=False)
    # ### end Alembic commands ###
