"""empty message

Revision ID: 3937b529b6d0
Revises: b8317bc250f2
Create Date: 2024-02-25 02:16:43.907651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3937b529b6d0'
down_revision: Union[str, None] = 'b8317bc250f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('course_id_idx', table_name='student_course')
    op.drop_index('student_id_idx', table_name='student_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('student_id_idx', 'student_course', ['student_id'], unique=False)
    op.create_index('course_id_idx', 'student_course', ['course_id'], unique=False)
    # ### end Alembic commands ###
