"""empty message

Revision ID: 55458c3e671b
Revises: 6d2744221156
Create Date: 2024-02-25 00:48:23.022822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55458c3e671b'
down_revision: Union[str, None] = '6d2744221156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('assignment_name', sa.String(length=100), nullable=False))
    op.drop_column('assignment', 'name')
    op.add_column('course', sa.Column('course_name', sa.String(length=100), nullable=False))
    op.drop_column('course', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('course', 'course_name')
    op.add_column('assignment', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('assignment', 'assignment_name')
    # ### end Alembic commands ###
