"""empty message

Revision ID: 6d2744221156
Revises: d0157ee22b22
Create Date: 2024-02-24 19:57:08.730933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d2744221156'
down_revision: Union[str, None] = 'd0157ee22b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('course', 'course_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('course', 'name')
    # ### end Alembic commands ###
