"""empty message

Revision ID: 8599bcf5ca4d
Revises: 3a4dc12c1cbf
Create Date: 2024-02-25 02:17:41.758579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8599bcf5ca4d'
down_revision: Union[str, None] = '3a4dc12c1cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
