"""empty message

Revision ID: a13843441652
Revises: c22759751a2d
Create Date: 2024-02-25 02:06:51.450373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13843441652'
down_revision: Union[str, None] = 'c22759751a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('student_course_id', table_name='student_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('student_course_id', 'student_course', ['id'], unique=False)
    # ### end Alembic commands ###
