"""empty message

Revision ID: b8317bc250f2
Revises: 1218f1208007
Create Date: 2024-02-25 02:15:04.610817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8317bc250f2'
down_revision: Union[str, None] = '1218f1208007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('course_id_idx', table_name='student_course')
    # op.drop_index('student_id_idx', table_name='student_course')
    op.create_index(op.f('ix_student_course_course_id'), 'student_course', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_student_id'), 'student_course', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_course_student_id'), table_name='student_course')
    op.drop_index(op.f('ix_student_course_course_id'), table_name='student_course')
    op.create_index('student_id_idx', 'student_course', ['student_id'], unique=False)
    op.create_index('course_id_idx', 'student_course', ['course_id'], unique=False)
    # ### end Alembic commands ###
