"""empty message

Revision ID: c4fe883c1fac
Revises: 91cc23693308
Create Date: 2024-02-25 02:00:02.777556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4fe883c1fac'
down_revision: Union[str, None] = '91cc23693308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_course', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('student_course', 'student_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_course', 'student_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('student_course', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
