"""empty message

Revision ID: d0157ee22b22
Revises: 57d6e39ea03f
Create Date: 2024-02-24 18:53:46.125835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0157ee22b22'
down_revision: Union[str, None] = '57d6e39ea03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('test', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
